language: php

matrix:
  fast_finish: true

php:
  - 5.6
  #- 7.1

  # cache vendor dirs
#cache:
#  directories:
#    - $HOME/.composer/cache
#    - vendor

services:
  - mysql

install:
  - travis_retry composer self-update
  - travis_retry composer global require "fxp/composer-asset-plugin:^1.2.0"
  - composer config -g github-oauth.github.com 1cfce87d43cdef633f435ab98ba051359fdd678a
  - travis_retry composer install --prefer-dist --no-interaction
  - travis_retry mysql -e 'CREATE DATABASE test;'

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
